# Generated by Django 2.0 on 2018-10-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
